//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shamyr.Cloud.Gateway.Service.Emails {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2019 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "3.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class EmailTemplates {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a EmailTemplates object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public EmailTemplates() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("Shamyr.Cloud.Gateway.Service.Emails.EmailTemplates", typeof(EmailTemplates).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Reset password'.
        /// </summary>
        public static string PasswordResetEmailSubject {
            get {
                return ResourceManager.GetString(ResourceNames.PasswordResetEmailSubject, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&lt;p&gt;
        ///    Click &lt;a href=&quot;**PORTAL_URL**login/passwordReset?userId=**USER_ID**&amp;passwordToken=**PASSWORD_TOKEN**&quot;&gt;HERE&lt;/a&gt; 
        ///    to reset your password for account with username &apos;**USERNAME**&apos;.
        ///&lt;/p&gt;'.
        /// </summary>
        public static string PasswordResetEmailTemplate {
            get {
                return ResourceManager.GetString(ResourceNames.PasswordResetEmailTemplate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Verify your account'.
        /// </summary>
        public static string VerifyAccountEmailSubject {
            get {
                return ResourceManager.GetString(ResourceNames.VerifyAccountEmailSubject, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '&lt;p&gt;
        ///    Click &lt;a href=&quot;**SERVER_URL**api/v1/emails/**EMAIL**/verify?emailToken=**VERIFY_TOKEN**&quot;&gt;HERE&lt;/a&gt; to verify your email.
        ///&lt;/p&gt;'.
        /// </summary>
        public static string VerifyAccountEmailTemplate {
            get {
                return ResourceManager.GetString(ResourceNames.VerifyAccountEmailTemplate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'PasswordResetEmailSubject'.
            /// </summary>
            public const string PasswordResetEmailSubject = "PasswordResetEmailSubject";
            
            /// <summary>
            /// Stores the resource name 'PasswordResetEmailTemplate'.
            /// </summary>
            public const string PasswordResetEmailTemplate = "PasswordResetEmailTemplate";
            
            /// <summary>
            /// Stores the resource name 'VerifyAccountEmailSubject'.
            /// </summary>
            public const string VerifyAccountEmailSubject = "VerifyAccountEmailSubject";
            
            /// <summary>
            /// Stores the resource name 'VerifyAccountEmailTemplate'.
            /// </summary>
            public const string VerifyAccountEmailTemplate = "VerifyAccountEmailTemplate";
        }
    }
}
