version: '3.4'

services:
  gateway:
    image: shamyr/cloud/gateway/service
    ports:
      - 8080:80
    environment:
      MONGO_URL: "mongodb://mongodb:27017"
      MONGO_DATABASE_NAME: "ShamyrIdentity"
      GATEWAY_URL: "http://localhost:8080/"
      PORTAL_URL: "http://localhost:3000/#/"
      BEARER_TOKEN_ISSUER: "Shamyr gateway"
      BEARER_TOKEN_AUDIENCE: "React"
      REFRESH_TOKEN_DURATION: "604800"
      BEARER_TOKEN_DURATION: "3600"
      BEARER_TOKEN_SYMETRIC_KEY: "U3j5QK5Q6xjRvTV1lKXqGvArG2zTuE9V9os3Out7JVfKEjmwToTPYx2uHk3fKCWpF1QnDamL958HJXQ9450k2Uze4jhC6k0B3TPod2Stb1VcVbbWc5PlVLjgDBLS0Cs1znqoUGRvW2st50OcRauPHWwcy3K0aZO1"
      EMAIL_SERVER_URL: "http://server.ladislavprix.cz/sendMail.php"
      EMAIL_SENDER_ADDRESS: "noreply@ladislavprix.cz"
    build:
      context: .
      dockerfile: ./src/Shamyr.Cloud.Gateway.Service/Dockerfile

  identity:
    image: shamyr/cloud/identity/service
    ports:
      - 8081:80
    environment:
      MONGO_URL: 'mongodb://mongodb:27017'
      MONGO_DATABASE_NAME: 'ShamyrIdentity'
      BEARER_TOKEN_ISSUER: "Shamyr gateway"
      BEARER_TOKEN_AUDIENCE: "React"
      BEARER_TOKEN_SYMETRIC_KEY: "U3j5QK5Q6xjRvTV1lKXqGvArG2zTuE9V9os3Out7JVfKEjmwToTPYx2uHk3fKCWpF1QnDamL958HJXQ9450k2Uze4jhC6k0B3TPod2Stb1VcVbbWc5PlVLjgDBLS0Cs1znqoUGRvW2st50OcRauPHWwcy3K0aZO1"
    build:
      context: .
      dockerfile: ./src/Shamyr.Cloud.Identity.Service/Dockerfile

  test:
    image: shamyr/cloud/identity/client/test
    ports:
      - 8082:80
    environment:
      IDENTITY_URL: 'http://identity:80/'
      GATEWAY_URL: 'http://gateway:80/'
      CLIENT_ID: '5f02d27b472aa34818a8bea8'
      CLIENT_SECRET: 'string'
    build:
      context: .
      dockerfile: ./src/Shamyr.Cloud.Identity.Client.Test/Dockerfile

  redis:
    image: redis:latest
    volumes:
      - redisdata:/data
    command: redis-server --maxmemory 500m --maxmemory-policy allkeys-lru

  mongodb:
    image: mongo:latest
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017

  swaggerui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "9595:8080"
    environment:
      API_URL: "http://localhost:8080/docs/v1/swagger.json"

volumes:
  redisdata:
  mongodata: