name: CI

on:
  push:
    branches: [ master ]

jobs:
  buildAndPushAuthority:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets. DOCKER_HUB_PASSWORD }}
          repository: shamyr/cloud-authority
          dockerfile: ./src/Shamyr.Cloud.Authority.Service/Dockerfile
          tags: latest
          tag_with_sha: true

  buildAndPushAuthority:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets. DOCKER_HUB_PASSWORD }}
            repository: shamyr/cloud-identity
            dockerfile: ./src/Shamyr.Cloud.Identity.Service/Dockerfile
            tags: latest
            tag_with_sha: true